### ISSUE TITLE
get_links fails on missing pageid

### ISSUE THREAD

**Issue by trifle** [mahmoud/wapiti#15]
Hi, thanks for your work on wapiti, it's a wonderful pythonic library!

I've had trouble with getting links on some pages. While

```
client.get_links("Coffee")
```

works, the following does not:

```
client.get_links("Aabach")
```

The problem seems to be that the API returns result pages with missing `pageid` parameters:

http://en.wikipedia.org/w/api.php?action=query&generator=links&titles=Aabach&prop=info

```
<?xml version="1.0"?>
<api>
  <query>
    <pages>
      <page ns="0" title="Aabachsee" missing="" contentmodel="wikitext" pagelanguage="en" />
      <page pageid="23868574" ns="0" title="Aa River (disambiguation)" contentmodel="wikitext" pagelanguage="en" touched="2013-05-19T19:24:27Z" lastrevid="352597402" counter="" length="49" redirect="" />
(...snip...)
```

For lack of time, I think I'll just patch the `extract_results` method on `GetLinks`, but it's probably worth considering a parameter to get_links that allows for silently ignoring the Exceptions instead of breaking?

**Comment by mahmoud** [comment]
Eek! You're right, red links don't have page ids, I'll patch that straight away.

In the meantime, feel free to hack away. It's definitely still a work in progress, but I'm glad you're enjoying it so far. Pull requests are more than welcome, too :)

**Comment by mahmoud** [comment]
Hey again, trifle,

I don't know if you noticed, but yesterday Bryan and I added (issue #19) an initial implementation of a feature that generically allows specification of whether to return only existing pages, only non-existent pages, or both (the default). Just pass `exists=True` or `exists=False` as a keyword argument into an operation. E.g.,

``` python
client.get_links("Aabach", exists=True)
```

I think about a quarter of operations have the possibility of returning non-existent pages. To keep the Wapiti model system from getting too crowded, we kept all the existing output types (mostly PageInfo), and set their `page_id` attribute to `None`. I feel like it's a semantically concise way to convey that the page hasn't been created yet, but it might break some more complex operations, so keep an eye on that if/when you try it out.

**Comment by trifle** [comment]
Hi mahmoud,

thanks, that should work beautifully.
And I agree that it's logical to have a representation of Wikipedia's red links. So I'll keep my eyes open for any internals that don't yet know how to handle those.

Thanks again for your work!
