### ISSUE TITLE
How to use get_revision_infos (page, limit) function?

### ISSUE THREAD

**Issue by vinhqdang** [mahmoud/wapiti#27]
Hello

I implemented a code like this:

client = wapiti.WapitiClient('domas@mituzas.lt')
page = client.get_random (10)[0]
client.get_revision_infos (page, 10)

but the last line generates an error.

Is it the correct way to use the function **get_revision_infos** ?

Could you give me some hints?

Thank you very much

**Comment by mahmoud** [comment]
That's true. The error you see likely looks like this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wapiti/client.py", line 63, in __call__
    self.op_inst = self.op_type(*a, **kw)
  File "wapiti/operations/base.py", line 485, in __init__
    super(QueryOperation, self).__init__(input_param, limit, **kw)
  File "wapiti/operations/base.py", line 322, in __init__
    self.set_input_param(input_param)
  File "wapiti/operations/base.py", line 348, in set_input_param
    self._input_param = self.input_field.get_value(param)
  File "wapiti/operations/params.py", line 165, in get_value
    value = self._coerce_value(value)
  File "wapiti/operations/params.py", line 160, in _coerce_value
    raise TypeError('could not coerce value %r to %r' % (value, self.key))
TypeError: could not coerce value PageInfo(title=u'Saint-Cyprien-sur-Dourdou', page_id=15438368, ns=0) to u'revids'
```

What this is saying is that the output of `get_random` is not the same as the input of `get_revision_infos`. The operation you likely want to use is `get_page_revision_infos` which can be coerced:

```
>>> client.get_page_revision_infos(page)
[RevisionInfo(title=u'User talk:76.240.197.166', page_id=21456919, ns=3, rev_id=269453603, timestamp=datetime.datetime(2009, 2, 9, 2, 58, 17))]
```

The Wikipedia API is very dense and so naming these operations is always a challenge. Sorry for the delay, hope that helped!

**Comment by vinhqdang** [comment]
Thank you very much

**Comment by vinhqdang** [comment]
Hello

I am sorry that I asked so much, but what I want to is getting the revision history of a page in wikipedia to see who edit what and when.

Could you give me some hints to get that information from the information of the function _get_page_revision_infos_

**Comment by mahmoud** [comment]
Just call `client.get_page_revision_infos('Title of the page')` to get all of a page's revision history. Pass a `limit` keyword parameter to get fewer. Right now there appears to be a print statement reporting warnings. You'll have to ignore those. :P

**Comment by vinhqdang** [comment]
So, for instance:

`[RevisionInfo(title=u'Aikido', page_id=751, ns=0, rev_id=655426768, timestamp=datetime.datetime(2015, 4, 8, 0, 9, 3)), RevisionInfo(title=u'Aikido', page_id=751, ns=0, rev_id=655156089, timestamp=datetime.datetime(2015, 4, 6, 8, 1)), RevisionInfo(title=u'Aikido', page_id=751, ns=0, rev_id=655138403, timestamp=datetime.datetime(2015, 4, 6, 4, 14, 7)), RevisionInfo(title=u'Aikido', page_id=751, ns=0, rev_id=654614690, timestamp=datetime.datetime(2015, 4, 2, 10, 13, 16)), RevisionInfo(title=u'Aikido', page_id=751, ns=0, rev_id=654613186, timestamp=datetime.datetime(2015, 4, 2, 9, 54, 59))]`

I have the revision ID and timestamp of each revision. Then how can I get the owner (i.e, who commited this revision), and what did he do?

I am sorry again if the question is too much.
